# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='users_who_like',
            field=models.ManyToManyField(related_name='favorites', to='login.User'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
